services:
  web:
    container_name: next-website
    image: ghcr.io/jaredy899/next-website:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped 